/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author fernandomarenco
 */
public class PanelBarcos extends javax.swing.JPanel {

    /**
     * Creates new form PanelBarcos
     */
    public PanelBarcos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtBuscarFolio = new javax.swing.JTextField();
        btnBuscarBarco = new javax.swing.JButton();
        btnAgregarBarco = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBarcos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnEditarBarco = new javax.swing.JButton();
        btnEliminarBarco = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 245, 245));
        setPreferredSize(new java.awt.Dimension(881, 492));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Buscar:");

        txtBuscarFolio.setText("Nombre");

        btnBuscarBarco.setBackground(new java.awt.Color(249, 183, 72));
        btnBuscarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnBuscarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search20x20White.png"))); // NOI18N
        btnBuscarBarco.setText("BUSCAR");
        btnBuscarBarco.setBorderPainted(false);
        btnBuscarBarco.setOpaque(true);

        btnAgregarBarco.setBackground(new java.awt.Color(55, 179, 68));
        btnAgregarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnAgregarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add20x20White.png"))); // NOI18N
        btnAgregarBarco.setText("AGREGAR");
        btnAgregarBarco.setBorderPainted(false);
        btnAgregarBarco.setOpaque(true);

        tblBarcos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del barco", "Responsable", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblBarcos);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Barcos:");

        btnEditarBarco.setBackground(new java.awt.Color(52, 150, 247));
        btnEditarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnEditarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit20x20White.png"))); // NOI18N
        btnEditarBarco.setText("EDITAR");
        btnEditarBarco.setBorderPainted(false);
        btnEditarBarco.setOpaque(true);

        btnEliminarBarco.setBackground(new java.awt.Color(237, 28, 36));
        btnEliminarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnEliminarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete20x20White.png"))); // NOI18N
        btnEliminarBarco.setText("ELIMINAR");
        btnEliminarBarco.setBorderPainted(false);
        btnEliminarBarco.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditarBarco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarBarco)
                .addGap(343, 343, 343))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarBarco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarBarco))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBarco)
                    .addComponent(btnAgregarBarco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarBarco)
                    .addComponent(btnEliminarBarco))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarBarco;
    private javax.swing.JButton btnBuscarBarco;
    private javax.swing.JButton btnEditarBarco;
    private javax.swing.JButton btnEliminarBarco;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblBarcos;
    private javax.swing.JTextField txtBuscarFolio;
    // End of variables declaration//GEN-END:variables
}
