/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perraespacial;



/**
 *
 * @author oscardena
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminReportes
     */
    public AdminView() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCargasReporte = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEntregasReporte = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        txtFechaFin = new javax.swing.JFormattedTextField();
        btnBuscarReporte = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblTotalMacarela = new javax.swing.JLabel();
        lblPctMacarela = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblTotalJaponesa = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblPctJaponesa = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblTotalMonterrey = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblPctMonterrey = new javax.swing.JLabel();
        lblTotalRayadillo = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblPctRayadillo = new javax.swing.JLabel();
        lblTotalBocona = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblPctBocona = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblTotalAnchoveta = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lblPctAnchoveta = new javax.swing.JLabel();
        lblPctCrinuda = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblTotalCrinuda = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarFolio = new javax.swing.JTextField();
        btnBuscarEntrada = new javax.swing.JButton();
        btnAgregarEntrada = new javax.swing.JButton();
        btnEditarEntrada = new javax.swing.JButton();
        btnEliminarEntrada = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnBuscarBarco = new javax.swing.JButton();
        btnAgregarBarco = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEditarBarco = new javax.swing.JButton();
        btnEliminarBarco = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblIniciales = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));

        jTabbedPane1.setBackground(new java.awt.Color(250, 250, 250));
        jTabbedPane1.setOpaque(true);

        tblCargasReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barco", "Especie", "Cantidad", "Talla", "Temperatura", "Condición"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCargasReporte);

        jLabel5.setText("Cargas");

        tblEntregasReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Entrega", "Generado por", "Turno", "Fecha", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblEntregasReporte);

        jLabel3.setText("Ingresar fecha");

        txtFechaInicio.setText("Inicio");

        txtFechaFin.setText("Fin");

        btnBuscarReporte.setBackground(new java.awt.Color(249, 183, 72));
        btnBuscarReporte.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBuscarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/search20x20White.png"))); // NOI18N
        btnBuscarReporte.setText("BUSCAR");
        btnBuscarReporte.setBorderPainted(false);
        btnBuscarReporte.setOpaque(true);

        btnGenerarReporte.setBackground(new java.awt.Color(52, 150, 247));
        btnGenerarReporte.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/reports20x20White.png"))); // NOI18N
        btnGenerarReporte.setText("GENERAR REPORTE");
        btnGenerarReporte.setBorderPainted(false);
        btnGenerarReporte.setOpaque(true);

        jLabel8.setText("Entregas");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Macarela");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Japonesa");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Monterrey");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("Rayadillo");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setText("Bocona");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setText("Anchoveta");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setText("Crinuda");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setText("Total");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel17.setText("Total:");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel18.setText("Prcentaje:");

        lblTotalMacarela.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblTotalMacarela.setText("jLabel19");

        lblPctMacarela.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblPctMacarela.setText("jLabel19");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel21.setText("Total:");

        lblTotalJaponesa.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblTotalJaponesa.setText("jLabel19");

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel23.setText("Prcentaje:");

        lblPctJaponesa.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblPctJaponesa.setText("jLabel19");

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel25.setText("Total:");

        lblTotalMonterrey.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblTotalMonterrey.setText("jLabel19");

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel27.setText("Prcentaje:");

        lblPctMonterrey.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblPctMonterrey.setText("jLabel19");

        lblTotalRayadillo.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblTotalRayadillo.setText("jLabel19");

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel30.setText("Total:");

        jLabel31.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel31.setText("Prcentaje:");

        lblPctRayadillo.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblPctRayadillo.setText("jLabel19");

        lblTotalBocona.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblTotalBocona.setText("jLabel19");

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel34.setText("Prcentaje:");

        lblPctBocona.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblPctBocona.setText("jLabel19");

        jLabel36.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel36.setText("Total:");

        jLabel37.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel37.setText("Total:");

        lblTotalAnchoveta.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblTotalAnchoveta.setText("jLabel19");

        jLabel39.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel39.setText("Prcentaje:");

        lblPctAnchoveta.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblPctAnchoveta.setText("jLabel19");

        lblPctCrinuda.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblPctCrinuda.setText("jLabel19");

        jLabel42.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel42.setText("Total:");

        lblTotalCrinuda.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblTotalCrinuda.setText("jLabel19");

        jLabel44.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel44.setText("Prcentaje:");

        lblTotal.setText("jLabel45");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarReporte)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnGenerarReporte))
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPctMacarela))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalMacarela))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPctBocona))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalBocona))
                            .addComponent(jLabel13))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPctJaponesa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalJaponesa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPctAnchoveta))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalAnchoveta)))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPctMonterrey))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalMonterrey))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPctCrinuda))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalCrinuda)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPctRayadillo))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalRayadillo)))
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel16)
                                    .addComponent(lblTotal))
                                .addGap(109, 109, 109))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReporte)
                    .addComponent(btnGenerarReporte))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(lblTotalMacarela))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(lblPctMacarela)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(lblTotalMonterrey))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(lblPctMonterrey)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(lblTotalRayadillo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(lblPctRayadillo)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(lblTotalJaponesa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lblPctJaponesa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel37)
                                            .addComponent(lblTotalAnchoveta))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel39)
                                            .addComponent(lblPctAnchoveta)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel42)
                                            .addComponent(lblTotalCrinuda))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel44)
                                            .addComponent(lblPctCrinuda)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(lblTotalBocona))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(lblPctBocona))))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Reportes", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Fecha", "Hora", "Turno", "Generado por"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setText("Buscar");

        txtBuscarFolio.setText("Folio");

        btnBuscarEntrada.setBackground(new java.awt.Color(249, 183, 72));
        btnBuscarEntrada.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBuscarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/search20x20White.png"))); // NOI18N
        btnBuscarEntrada.setText("BUSCAR");
        btnBuscarEntrada.setBorderPainted(false);
        btnBuscarEntrada.setOpaque(true);

        btnAgregarEntrada.setBackground(new java.awt.Color(55, 179, 68));
        btnAgregarEntrada.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAgregarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/add20x20White.png"))); // NOI18N
        btnAgregarEntrada.setText("AGREGAR");
        btnAgregarEntrada.setBorderPainted(false);
        btnAgregarEntrada.setOpaque(true);

        btnEditarEntrada.setBackground(new java.awt.Color(52, 150, 247));
        btnEditarEntrada.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnEditarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/edit20x20White.png"))); // NOI18N
        btnEditarEntrada.setText("EDITAR");
        btnEditarEntrada.setBorderPainted(false);
        btnEditarEntrada.setOpaque(true);

        btnEliminarEntrada.setBackground(new java.awt.Color(237, 28, 36));
        btnEliminarEntrada.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnEliminarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/delete20x20White.png"))); // NOI18N
        btnEliminarEntrada.setText("ELIMINAR");
        btnEliminarEntrada.setBorderPainted(false);
        btnEliminarEntrada.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarEntrada)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarEntrada)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarEntrada))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEntrada)
                    .addComponent(btnAgregarEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEntrada)
                    .addComponent(btnEliminarEntrada))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Entradas", jPanel3);
        jPanel3.getAccessibleContext().setAccessibleName("");

        jLabel4.setText("Buscar");

        jTextField1.setText("Nombre");

        btnBuscarBarco.setBackground(new java.awt.Color(249, 183, 72));
        btnBuscarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBuscarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/search20x20White.png"))); // NOI18N
        btnBuscarBarco.setText("BUSCAR");
        btnBuscarBarco.setBorderPainted(false);
        btnBuscarBarco.setOpaque(true);

        btnAgregarBarco.setBackground(new java.awt.Color(55, 179, 68));
        btnAgregarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAgregarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/add20x20White.png"))); // NOI18N
        btnAgregarBarco.setText("AGREGAR");
        btnAgregarBarco.setBorderPainted(false);
        btnAgregarBarco.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del barco", "Responsable", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        btnEditarBarco.setBackground(new java.awt.Color(52, 150, 247));
        btnEditarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnEditarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/edit20x20White.png"))); // NOI18N
        btnEditarBarco.setText("EDITAR");
        btnEditarBarco.setBorderPainted(false);
        btnEditarBarco.setOpaque(true);

        btnEliminarBarco.setBackground(new java.awt.Color(237, 28, 36));
        btnEliminarBarco.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnEliminarBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/delete20x20White.png"))); // NOI18N
        btnEliminarBarco.setText("ELIMINAR");
        btnEliminarBarco.setBorderPainted(false);
        btnEliminarBarco.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(btnEditarBarco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarBarco)
                .addGap(89, 89, 89))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarBarco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarBarco)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBarco)
                    .addComponent(btnAgregarBarco))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarBarco)
                    .addComponent(btnEliminarBarco))
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Barcos", jPanel4);

        jLabel7.setText("Buscar");

        jTextField2.setText("Nombre");

        jButton1.setBackground(new java.awt.Color(249, 183, 72));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/search20x20White.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);

        jButton2.setBackground(new java.awt.Color(55, 179, 68));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/add20x20White.png"))); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(true);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre completo", "Rol", "RFC", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel5);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/exit50x50Black.png"))); // NOI18N
        btnLogout.setBorderPainted(false);

        lblUsername.setText("Nombre User");

        lblIniciales.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblIniciales.setText("NU");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perraespacialimages/SpaceDogLogo.png"))); // NOI18N
        jLabel1.setSize(new java.awt.Dimension(50, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Space Dog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIniciales)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIniciales)
                    .addComponent(lblUsername)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarBarco;
    private javax.swing.JButton btnAgregarEntrada;
    private javax.swing.JButton btnBuscarBarco;
    private javax.swing.JButton btnBuscarEntrada;
    private javax.swing.JButton btnBuscarReporte;
    private javax.swing.JButton btnEditarBarco;
    private javax.swing.JButton btnEditarEntrada;
    private javax.swing.JButton btnEliminarBarco;
    private javax.swing.JButton btnEliminarEntrada;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblIniciales;
    private javax.swing.JLabel lblPctAnchoveta;
    private javax.swing.JLabel lblPctBocona;
    private javax.swing.JLabel lblPctCrinuda;
    private javax.swing.JLabel lblPctJaponesa;
    private javax.swing.JLabel lblPctMacarela;
    private javax.swing.JLabel lblPctMonterrey;
    private javax.swing.JLabel lblPctRayadillo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalAnchoveta;
    private javax.swing.JLabel lblTotalBocona;
    private javax.swing.JLabel lblTotalCrinuda;
    private javax.swing.JLabel lblTotalJaponesa;
    private javax.swing.JLabel lblTotalMacarela;
    private javax.swing.JLabel lblTotalMonterrey;
    private javax.swing.JLabel lblTotalRayadillo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblCargasReporte;
    private javax.swing.JTable tblEntregasReporte;
    private javax.swing.JTextField txtBuscarFolio;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
